# Generated by Django 6.1 on 2026-08-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'legal_documents',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('document_type', 'version'), name='unique_document_version'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document_type',), name='unique_active_document_per_type')],
            },
        ),
    ]
