# Generated by Django 6.1 on 2026-08-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legaldocument',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='legaldocument',
            name='unique_document_version',
        ),
        migrations.RemoveConstraint(
            model_name='legaldocument',
            name='unique_active_document_per_type',
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='content',
            field=models.TextField(blank=True, default='Content goes here...'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy')], max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='legaldocument',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='legaldocument',
            name='version',
        ),
    ]
